insert into assets (name, serial_number, specifications)
values ('keyboard', '19467001725', '{
  "brand": "Logitech",
  "numberOfButtons": 1,
  "keyboardDescription": "Multi Functional",
  "numberOfKeys": 1,
  "model": "920-007558",
  "modelName": "K380",
  "modelYear": "2015",
  "productDimensions": " 27.69 x 12.45 x 1.52 cm; 408.23 Grams",
  "batteries": "1 A batteries required. (included)",
  "itemModelNumber": " 920-007558",
  "hardwarePlatform": " PC: Windows 7, Windows 8, Windows 10 or later Mac: Mac OS 10.10 or later Chrome OS Android tablet or smartphone: Android 3.2 or later. iPad or iPhone: iOS 5 or later Apple TV 2nd or 3rd generation",
  "hardwareInterface": " Bluetooth",
  "compatibleDevices": " Laptop, PC, Tablet",
  "specialFeatures": " Bluetooth",
  "mountingHardware": " Bluetooth Keyboard",
  "aspectRatio": "Unknown",
  "batteryAverageLife": "17520 Hours",
  "batteriesIncluded": "Yes",
  "batteriesRequired": "Yes",
  "batteryCellComposition": "Lithium Ion",
  "wirelessType": "Bluetooth",
  "connectorType": "Wireless",
  "containsLiquidContents": "No",
  "manufacturer": "Logitech",
  "countryOfOrigin": "China",
  "itemWeight": "408 g"
}'),
       ('keyboard', '18463001221', '{
         "brand": "Logitech",
         "model": "920-006342",
         "modelYear": "2014",
         "productDimensions": "30.99 x 4.09 x 20.1 cm; 821 Grams",
         "batteries": "1 Lithium Polymer batteries required. (included)",
         "itemModelNumber": "920-006342",
         "hardwarePlatform": "Bluetooth",
         "hardwareInterface": "Bluetooth",
         "compatibleDevices": "Laptop, PC, Tablet, Smartphone",
         "specialFeatures": "Basic",
         "mountingHardware": "Keyboard 2 AAA batteries (pre-installed) User documentation",
         "batteriesIncluded": "Yes",
         "batteriesRequired": "Yes",
         "batteryCellComposition": "Alkaline",
         "connectorType": "Wireless",
         "containsLiquidContents": "No",
         "hasAutoFocus": "No",
         "includesRechargeableBattery": "No",
         "programmableButtons": "No",
         "manufacturer": "Logitech",
         "itemWeight": "821 g"
       }'),
       ('keyboard', '12411201332', '{
         "brand": "Amkette",
         "colour": "Black",
         "itemHeight": "4.02 Centimeters",
         "itemWidth": "13 Centimeters",
         "productDimensions": "52 x 13 x 4.02 cm; 625 Grams",
         "batteries": "4 AAA batteries required. (included)",
         "itemModelNumber": "Primus",
         "wirelessType": "2.4 GHz Radio Frequency",
         "powerSource": "DC",
         "operatingSystem": "Laptop, PC, Mac, Android",
         "areBatteriesIncluded": "Yes",
         "includedComponents": "Keyboard, mouse, 4AAA batteries, USB Nano receiver",
         "manufacturer": "Allied Electronics And Magnetics Private Limited",
         "countryOfOrigin": "China",
         "itemWeight": "625 g"
       }'),
       ('monitor', '184619467121', '{
         "model": "32QN600",
         "modelName": "IPS Monitor",
         "productDimensions": "20.9 x 71.4 x 51.2 cm; 7.2 Kilograms",
         "itemModelNumber": "32QN600",
         "hardwareInterface": "DisplayPort, HDMI",
         "responseTime": "5 Milliseconds",
         "specialFeatures": "Anti Glare Screen, QHD (2560 x 1440) Resolution with HDR 10, Blue Light Filter, Wall Mountable, Thin Bezel, Tilt Adjustment, Flicker-Free",
         "mountingHardware": "1 Unit of Monitor, 1 Unit of adapter & cable",
         "displayTechnology": "LCD",
         "standingScreenDisplaySize": "31.5 Inches",
         "displayType": "LED",
         "imageBrightness": "350 cd / m²",
         "resolution": "2560x1440",
         "batteriesRequired": "No",
         "refreshRate": "75",
         "connectorType": "HDMI",
         "mountingType": "Wall Mount",
         "manufacturer": "LG Electronics Nanjing New Technology Co.,Ltd",
         "countryOfOrigin": "China",
         "importedBy": "LG Electronics India Pvt Ltd",
         "itemWeight": "7 kg 200 g"
       }'),
       ('monitor', '124113427321', '{
         "brand": "Acer",
         "manufacturer": "Acer India Pvt Ltd",
         "model": "ET322QK",
         "modelYear": "2018",
         "productDimensions": "24.64 x 72.9 x 52.83 cm; 5.62 Kilograms",
         "itemModelNumber": "ET322QK",
         "hardwareInterface": "DisplayPort, HDMI",
         "responseTime": "4 Milliseconds",
         "specialFeatures": "Blue Light Filter, Wall Mountable, Flicker-Free, Built-In Speakers",
         "mountingHardware": "Main Unit and Power Cord",
         "numberOfItems": "5",
         "displayTechnology": "LED",
         "standingScreenDisplaySize": "31.5 Inches",
         "displayType": "LED",
         "viewingAngle": "178 Degrees",
         "imageAspectRatio": "16:9",
         "imageBrightness": "300 cd / m²",
         "imageContrastRatio": "3000:1",
         "aspectRatio": "16:9",
         "resolution": "3840 x 2160 Pixels",
         "maxVerticalResolution": "2160 Pixels",
         "speakersNominalOutputPower": "2 Watts",
         "voltage": "120 Volts",
         "wattage": "4 Watts",
         "batteriesIncluded": "No",
         "batteriesRequired": "No",
         "refreshRate": "60 Hz",
         "connectorType": "DisplayPort, HDMI",
         "realAngleOfView": "178 Degrees",
         "containsLiquidContents": "No",
         "countryOfOrigin": "China",
         "importedBy": "ACER INDIA PRIVATE LIMITED Embassy Heights, 6th Floor, No. 13 Magrath Road, Next to HOSMAT Hospital, Bangalore, INDIA – 560030",
         "itemWeight": "5 kg 620 g"
       }'),
       ('laptop', '112113427331', '{
         "series": "Pavilion x360",
         "colour": "Mineral Silver",
         "itemHeight": "2.1 Centimeters",
         "itemWidth": "22.3 Centimeters",
         "standingScreenDisplaySize": "14 Inches",
         "resolution": "1920 x 1080 Pixels",
         "product Dimensions": "32.4 x 22.3 x 2.1 cm; 1.58 Kilograms",
         "batteries": "1 Lithium ion batteries required. (included)",
         "itemModelNumber": "14-dh1178tu",
         "processorBrand": "Intel",
         "processorType": "Core i3",
         "processorSpeed": "2.1 GHz",
         "processorCount": "1",
         "ramSize": "8 GB",
         "memoryTechnology": "DDR4",
         "computerMemoryType": "DDR4 SDRAM",
         "maximumMemorySupported": "16 GB",
         "hardDiskDescription": "SSD",
         "hardDriveInterface": "USB 3.1",
         "speakerDescription": "B&O, dual speakers, HP Audio Boost",
         "graphicsCoprocessor": "Intel UHD",
         "graphicsChipsetBrand": "Intel",
         "graphicsCardDescription": "Integrated",
         "graphicsRAMType": "VRAM",
         "graphicsCardInterface": "Integrated",
         "connectivityType": "Bluetooth, Wi-Fi",
         "numberOfUSB3Ports": "2",
         "numberOfHDMIPorts": "1",
         "numberOfAudioOutPorts": "1",
         "numberOfEthernetPorts": "1",
         "opticalDriveType": "No Optical Drive",
         "powerSource": "Battery Powered",
         "operatingSystem": "Windows 10 Home",
         "supportedSoftware": "Comes with Preinstalled Microsoft Office Home & Student 2019",
         "averageBatteryStandbyLife": "7 Hours",
         "averageBatteryLife": "7 Hours",
         "areBatteriesIncluded": "Yes",
         "lithiumBatteryEnergyContent": "41 Watt Hours",
         "lithiumBatteryWeight": "0.85 Grams",
         "numberOfLithiumIonCells": "3",
         "includedComponents": "Laptop, Battery, AC Adapter, User Guide, Manuals",
         "manufacturer": "hp",
         "countryOfOrigin": "China",
         "importedBy": "HP India Sales Pvt. Ltd.",
         "itemWeight": "1 kg 580 g"
       }'),
       ('laptop', '1023134376434', '{
         "brand": "Dell",
         "manufacturer": "Dell India Pvt Ltd, Dell",
         "series": "Inspiron",
         "colour": "Silver",
         "formFactor": "Laptop",
         "itemHeight": "20 Millimeters",
         "itemWidth": "34 Centimeters",
         "standingScreenDisplay size": "14 Inches",
         "resolution": "1366x768",
         "productDimensions": "24 x 34 x 2 cm; 1.7 Kilograms",
         "batteries": "1 Lithium ion batteries required. (included)",
         "itemModelNumber": "3493",
         "processorBrand": "Intel",
         "processorType": "Core i3",
         "processorSpeed": "1.2 GHz",
         "processorCount": "1",
         "ramSize": "4 GB",
         "memoryTechnology": "DDR4",
         "maximumMemorySupported": "16 GB",
         "memoryClockSpeed": "2666 MHz",
         "hardDriveSize": "1 TB",
         "hardDiskDescription": "Mechanical Hard Drive",
         "hardDriveInterface": "Serial ATA",
         "hardDiskRotationalSpeed": "5400 RPM",
         "speakerDescription": "Waves Maxx",
         "graphicsCoprocessor": "Intel HD",
         "graphicsChipsetBrand": "Intel",
         "graphicsCardDescription": "Integrated",
         "graphicsRAMType": "Shared",
         "graphicsCardInterface": "Integrated",
         "connectivityType": "Wi-Fi, Bluetooth-V4",
         "wirelessType": "801.11ac",
         "numberOfUSB 2.0 Ports": "1",
         "numberOfUSB 3.0 Ports": "2",
         "numberOfHDMI Ports": "1",
         "numberOfAudio-out Ports": "1",
         "numberOfEthernet Ports": "1",
         "numberOfMicrophone Ports": "1",
         "frontWebcamResolution": "1 MP",
         "powerSource": "Battery Powered",
         "operatingSystem": "Windows 10",
         "averageBatteryStandbyLife": "7 Hours",
         "averageBatteryLife": "7 Hours",
         "areBatteriesIncluded": "Yes",
         "lithiumBatteryEnergyContent": "42 Watt Hours",
         "lithiumBatteryWeight": "0.85 Grams",
         "numberOfLithiumIonCells": "3",
         "includedComponents": "Laptop, Adapter, Power Cable",
         "importedBy": "Dell",
         "itemWeight": "1 kg 700 g"
       }'),
       ('mouse', '3021331376231', '{
         "brand": "Dell",
         "itemHeight": "14.2 Centimeters",
         "itemWidth": "46 Millimeters",
         "productDimensions": "9.1 x 4.6 x 14.2 cm; 140 Grams",
         "manufacturer": "Dell Computers",
         "countryOfOrigin": "India",
         "itemWeight": "140 g"
       }'),
       ('mouse', '20131241316231', '
       {
         "brand": "Logitech",
         "manufacturer": "Logitech",
         "colour": "Black",
         "itemHeight": "35 Millimeters",
         "itemWidth": "6.2 Centimeters",
         "productDimensions": "9.8 x 6.2 x 3.5 cm; 68 Grams",
         "batteries": "1 A batteries required. (included)",
         "itemModelNumber": "B170",
         "wirelessType": "2.4 GHz Radio Frequency",
         "operatingSystem": "Chrome os, Windows 8, Windows 7, Mac os, Windows 10",
         "averageBatteryLife (in hours)": "12 Months",
         "areBatteriesIncluded": "Yes",
         "includedComponents": "Wireless Mouse, USB Receiver, 1 AA Battery (Pre-Installed), User Documentation",
         "countryOfOrigin": "China",
         "itemWeight": "68 g"
       }'),
       ('ups', '1033123126231', '{
         "brand": "APC",
         "manufacturer": "APC",
         "model": "BX600C-IN",
         "modelName": "BX600C-IN",
         "productDimensions": "23.7 x 10.7 x 21.8 cm; 4.69 Kilograms",
         "batteries": "1 Lithium Polymer batteries required. (included)",
         "itemModelNumber": "BX600C-IN",
         "specialFeatures": "Automatic Voltage Regulation (AVR) corrects incoming voltage, Compatible with low power loads e.g. wifi router, DSL modem, Faster charging 4-6 hours, 2 Year Warranty: covers parts & labor, including battery, Separate Charging LED",
         "mountingHardware": "UPS, User Manual and Warranty card",
         "numberOfItems": "1",
         "audioWattage": "360 Watts",
         "wattage": "360 Watts",
         "batteryAverage Life": "3 Years",
         "batteryAverage Life Standby": "20 Minutes",
         "chargingTime": "4 Hours",
         "batteriesIncluded": "Yes",
         "batteriesRequired": "Yes",
         "batteryCellComposition": "Lead Acid",
         "hasAutoFocus": "No",
         "programmableButtons": "No",
         "countryOfOrigin": "India",
         "itemWeight": "4 kg 690 g"
       }');

